# Generated by Django 4.0 on 2022-03-16 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('permalink', models.CharField(max_length=50)),
                ('body_text', models.TextField(blank=True, null=True, verbose_name='Page content')),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
